### ISSUE TITLE
irdb character set

### ISSUE THREAD

**Issue by asedeno** [bengtmartensson/RemoteLocator#3]
https://github.com/bengtmartensson/RemoteLocator/blob/ea6ada77ce699b17c54c581723064894387161ab/src/main/java/org/harctoolbox/remotelocator/IrdbScrap.java#L47-L51

I would go with `UTF-8` (less liberal in what is valid) or `ISO-8859-1` over `WINDOWS-1252`. At present, file(1) detects **all** irdb content as `ASCII text`, so this makes no difference now and is really about predicting the future. I wonder what @probonopd says.

**Comment by bengtmartensson** [comment]
Thank you for the comment. 

Of the one-byte character sets, Windows-1252 is the most "liberal" (i.e. with least "holes") one. Being a super set of ISO-8859-1, there are no compatibility problems. 

If IRDB officially goes UTF-8, I will change accordingly. Until then, I believe that Windows-1252 is the choice that maximizes usability. (I use that character set to parse Lirc files...) If I have missed some argument I will gladly reconsider.

**Comment by asedeno** [comment]
You're totally right, and after looking a little more closely, I completely agree. 👍

**Comment by probonopd** [comment]
> If IRDB officially goes UTF-8

Should we?

**Comment by bengtmartensson** [comment]
Strictly speaking, in these days, you should not publish text files without telling which character set they are using.  Particularly  not if you are accepting public submissions.

It is one advantage of using [Girr](https://github.com/probonopd/irdb/discussions/58), that it, as XML, comes with a character set declaration. (If empty, per XML specification it defaults to UTF-8). 

Since (to my knowledge, but I may be wrong) there is (presently!) not a single non-ascii character in the files, it is not exactly urgent...

**Comment by asedeno** [comment]
@bengtmartensson, yeah, that matches my scan of IRDB as of last week. It's all `ASCII`.

@probonopd, declaring a character encoding for IRDB would be worthwhile. I would tend towards `UTF-8`, which is encoded as a strict superset of `ASCII`, and supports all Unicode codepoints. Given the entire IRDB is `ASCII` now, declaring it `UTF-8` involves no changes to the csv files themselves. At that point it would be worth having something checking new PRs and commits to ensure that new edits are valid `UTF-8`.

Putting it off only really becomes an issue if/once any non-`ASCII` shows up.
